name: Campioni
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: For Italy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d0b8'
    - '#bcb0b0'
    - '#4f3423'
    - '#755139'
    - '#978d95'
  brandStrength: 0.9375
  lightness: 0.6379729206673801
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
